[API-19745] Add strict mode flag and validation
Signed-off-by: Nick Luckey <nickluckey@gmail.com>

diff --git a/.github/actions/validate-techdocs/action.yml b/.github/actions/validate-techdocs/action.yml
--- a/.github/actions/validate-techdocs/action.yml
+++ b/.github/actions/validate-techdocs/action.yml
@@ -14,6 +14,10 @@ inputs:
   token:
     description: "Personal Access token to pull source repository"
     required: false
+  strict-mode:
+    description: "Used to enable or disables strict flag for validation"
+    default: "true"
+    required: false
 outputs:
   results:
     description: "Results of validation script"
@@ -21,6 +25,15 @@ outputs:
 runs:
   using: "composite"
   steps:
+    - name: Setup validation args
+      id: args
+      run: |
+        local args
+        if [[ ${{ inputs.strict-mode == 'true' }} ]]; then
+          args+="--strict "
+        fi
+        echo "::set-output name=args::${args}"
+      shell: bash
     - name: Run validation script
       id: validation
       env:
@@ -28,14 +41,19 @@ runs:
         ENTITY_FILE: ${{ inputs.descriptor-file }}
         NAMESPACE: ${{ inputs.namespace }}
         TOKEN: ${{ inputs.token }}
+        ARGS: ${{ steps.args.outputs.args }}
       run: |
         /bin/bash <(curl -s https://${{ inputs.token }}@raw.githubusercontent.com/department-of-veterans-affairs/lighthouse-github-actions/main/scripts/validate-techdocs.sh)
       shell: bash
     - name: Check for errors
       run: |
+        if echo "${{ steps.validation.outputs.RESULTS }}" | grep -i "warning"; then
+          echo -e "Validation Error:\n${{ steps.validation.outputs.RESULTS }}";
+          exit 1;
+        fi
         if echo "${{ steps.validation.outputs.RESULTS }}" | grep -i "error"; then
           if echo "${{ steps.validation.outputs.RESULTS }}" | grep -i "failed to run plantuml"; then
-            echo -e "An error occurred with Plantuml.\nMake sure to use the @startuml and @enduml notation."
+            echo -e "Validation Error: Unable to create diagram with Plantuml.\nMake sure to use the @startuml and @enduml notation."
           fi
           exit 1;
         fi
