[API-19475] Added validate job, action, and script
Signed-off-by: Nick Luckey <nickluckey@gmail.com>

diff --git a/.github/workflows/build-publish-docs.yml b/.github/workflows/build-publish-docs.yml
--- a/.github/workflows/build-publish-docs.yml
+++ b/.github/workflows/build-publish-docs.yml
@@ -11,7 +11,23 @@ env:
   TOKEN: ${{ github.event.client_payload.token != '' && github.event.client_payload.token || secrets.TECHDOCS_PAT }}
   NAMESPACE: ${{ github.event.client_payload.namespace != '' &&  github.event.client_payload.namespace || secrets.KUBE_NAMESPACE }}
 jobs:
+  validate-techdocs:
+    runs-on: ubuntu-latest
+    steps:
+      - name: ${{ github.event.client_payload.sha }} # Used to return success or fail to the source repo
+        run: echo "${{ github.event.client_payload.sha }}"
+      - name: Validate techdocs
+        id: validation
+        uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/validate-techdocs@API-19475-validate-techdocs
+        with:
+          repository: ${{ env.REPO }}
+          descriptor-file: ${{ github.event.client_payload.descriptor-file }}
+          namespace: ${{ env.NAMESPACE }}
+          token: ${{ env.TOKEN }}
+      - name: return signal
+        run: exit ${{ steps.validation.output.exit-code }}
   build-techdocs:
+    needs: [validate-techdocs]
     runs-on: ubuntu-latest
     strategy:
       matrix:
@@ -22,7 +38,7 @@ jobs:
       - name: ${{ github.event.client_payload.sha }}
         run: echo "${{ github.event.client_payload.sha }}"
       - name: Create techdocs
-        uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs@main
+        uses: department-of-veterans-affairs/lighthouse-github-actions/.github/actions/techdocs@API-19475-validate-techdocs
         with:
           kubeconfig: ${{ secrets.KUBE_CONFIG }}
           kube_namespace: ${{ secrets.KUBE_NAMESPACE }}
@@ -35,6 +51,7 @@ jobs:
           PAT: ${{ secrets.TECHDOCS_PAT }}
   deploy-gh-pages:
     if: ${{ github.event.client_payload.gh-pages == 'true' || github.event_name != 'repository_dispatch' }}
+    needs: [validate-techdocs]
     runs-on: ubuntu-latest
     steps:
       - uses: actions/checkout@v3
